# plugins/restaurant-menu/restaurant-menu.config.yaml
oshea_plugin: restaurant-menu
description: "Plugin for generating restaurant menus"
handler_script: "index.js"
pdf_options:
  format: Letter # Or 'A4', 'Legal', etc. based on desired menu size
  margin:
    top: 0.75in
    right: 0.75in
    bottom: 0.75in
    left: 0.75in
css_files:
  - "restaurant-menu.css"
# You can add custom parameters here if needed, accessible via pluginSpecificConfig.params
params:
  logo_file: "./logo.jpg" # This can be used if you want to allow configuration of the logo path via config
